export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const SET_FIELDS = 'SET_FIELDS';
export const FETCH_DELETE_USER = 'FETCH_DELETE_USER';
